export enum RouteName {
  Home = 'Home',
  SignIn = 'SignIn',
  SignUp = 'SignUp',
  VerifyOtp = 'VerifyOtp',
  ForgotPassword = 'ForgotPassword',
  ResetPassword = 'ResetPassword',
  ChangePassword = 'ChangePassword',
  Dashboard = 'Dashboard',
  StoreProducts = 'StoreProducts',
  StoreOrder = 'StoreOrder',
  Pricing = 'Pricing',
   MomoPayment = 'MomoPayment',
   ReportDetail = 'ReportDetail',
   SetupShifts = 'SetupShifts',
   Settings = 'Settings',
   StoreOrdersManagement = 'StoreOrdersManagement',
   NotFound = 'NotFound',
  AdminDashboard = 'AdminDashboard',
  AdminStores = 'AdminStores',
  AdminUsers = 'AdminUsers',
  AdminSubscriptions = 'AdminSubscriptions',
  AdminSettings = 'AdminSettings',
}

export enum RoutePath {
  Home = '/',
  SignIn = '/signin',
  SignUp = '/signup',
  VerifyOtp = '/verify-otp',
  Dashboard = '/',
  StoreProducts = '/store/products',
  StoreOrder = '/store/order',
  Pricing = '/pricing',
  MomoPayment = '/payment/momo',
  ReportDetail = '/report',
  SetupShifts = '/setup-shifts',
  Settings = '/settings',
  Admin = '/admin',
  AdminDashboard = '/admin',
  AdminStores = '/admin/stores',
  AdminUsers = '/admin/users',
  AdminSubscriptions = '/admin/subscriptions',
  AdminSettings = '/admin/settings',
}
