export enum RouteName {
  Home = 'Home',
  SignIn = 'SignIn',
  SignUp = 'SignUp',
  VerifyOtp = 'VerifyOtp',
  ForgotPassword = 'ForgotPassword',
  ResetPassword = 'ResetPassword',
  ChangePassword = 'ChangePassword',
  Dashboard = 'Dashboard',
  StoreProducts = 'StoreProducts',
  StoreOrder = 'StoreOrder',
  Pricing = 'Pricing',
   MomoPayment = 'MomoPayment',
   ReportDetail = 'ReportDetail',
   SetupShifts = 'SetupShifts',
   Settings = 'Settings',
   StoreOrdersManagement = 'StoreOrdersManagement',
   NotFound = 'NotFound',
  AdminDashboard = 'AdminDashboard',
  AdminStores = 'AdminStores',
  AdminUsers = 'AdminUsers',
  AdminSubscriptions = 'AdminSubscriptions',
  AdminSettings = 'AdminSettings',
}
